name: CI/CD workflow

on:
  push:
    branches:
      - main

jobs:
  sync-repos:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Sync repos
      uses: jakejarvis/sync-repos@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        org: JMO-py-E-Commerce
        repo-filter: "*"
